const oracledb = require("oracledb");
const database = require("../services/database.js");

const baseQuery = `SELECT FA.ID, FA.ENT_ID, FA.AUDIT_CODE, NVL(FDD.IND_VALUE,AE.ENT_NAME) ENT_NAME, 
CASE WHEN RBT.BUDGET_TYPE_ID = 3 AND SE.BUDGET_TYPE_ID = 5 THEN 'Анхан шатны эмнэлэг' ELSE RBT.BUDGET_SHORT_NAME END BUDGET_NAME,
COUNT(SC.SURVEY_ID) ||'/'|| COUNT(RS.SURVEY_AUDIT_ID) STATUS,
SU.USER_NAME, SU.USER_CODE 
FROM FAS_ADMIN.FAS_AUDIT FA
INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
INNER JOIN FAS_ADMIN.FAS_ENT_EMAIL EE ON FA.ENT_ID = EE.ENT_ID
LEFT JOIN AUD_REG.SYSTEM_USER SU ON EE.CREATED_BY = SU.USER_ID
LEFT JOIN FAS_ADMIN.FAS_DOCUMENT_DATA FDD ON FA.ID = FDD.FAS_AUDIT_ID AND FDD.IS_ACTIVE = 1 AND FDD.IND_ID IN (287, 344)
LEFT JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
LEFT JOIN AUD_PUBLIC.REF_SURVEY_ENTITY SE ON FA.ID = SE.SURVEY_AUDIT_ID
LEFT JOIN AUD_PUBLIC.REF_SURVEY_CONFIG SC ON SE.BUDGET_TYPE_ID = SC.BUDGET_TYPE_ID 
LEFT JOIN AUD_PUBLIC.REG_SURVEY RS ON SC.SURVEY_ID = RS.SURVEY_ID AND FA.ID = RS.SURVEY_AUDIT_ID AND RS.SURVEY_STATUS_ID != 1
WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1`;

async function postList(context) {
  let query = baseQuery;

  const binds = {};
  if (context.usertype === "ADMIN") {
    query += `\n AND 1 = 1 `;
  } else {
    binds.USER_ID = context.userid;
    query += `\n AND EE.CREATED_BY = :USER_ID`;
  }
  query += `\n GROUP BY FA.ID, FA.ENT_ID, FA.AUDIT_CODE, NVL(FDD.IND_VALUE,AE.ENT_NAME),
  CASE WHEN RBT.BUDGET_TYPE_ID = 3 AND SE.BUDGET_TYPE_ID = 5 THEN 'Анхан шатны эмнэлэг' ELSE RBT.BUDGET_SHORT_NAME END, SU.USER_NAME, SU.USER_CODE`;
  query += `\n ORDER BY NVL(FDD.IND_VALUE,AE.ENT_NAME)`;
  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.postList = postList;
