const oracledb = require("oracledb");
const database = require("../services/database.js");

const baseQuery = `SELECT FA.CHECK_DEPARTMENT_ID, CD.DEPARTMENT_NAME, COUNT(EM.ID) EMAIL, SUM(A.S1) S1, SUM(A.S2_1) S2_1, SUM(A.S2_2) S2_2, SUM(A.S2_3) S2_3, 
SUM(A.S3) S3, SUM(A.S4) S4, SUM(A.S5) S5, SUM(A.S6) S6, SUM(A.S7) S7, SUM(A.S8) S8, SUM(A.S9) S9, SUM(A.S10) S10   
FROM FAS_ADMIN.FAS_AUDIT FA
INNER JOIN FAS_ADMIN.REF_CHECK_DEPARTMENT CD ON FA.CHECK_DEPARTMENT_ID = CD.ID
LEFT JOIN FAS_ADMIN.FAS_ENT_EMAIL EM ON FA.ID = EM.FAS_AUDIT_ID
LEFT JOIN (
SELECT RS.SURVEY_AUDIT_ID, 
COUNT(RS1.ID) S1, 
COUNT(RS21.ID) S2_1, 
COUNT(RS22.ID) S2_2, 
COUNT(RS23.ID) S2_3, 
COUNT(RS3.ID) S3, 
COUNT(RS4.ID) S4, 
COUNT(RS5.ID) S5, 
COUNT(RS6.ID) S6, 
COUNT(RS7.ID) S7, 
COUNT(RS8.ID) S8, 
COUNT(RS9.ID) S9, 
COUNT(RS10.ID) S10  
FROM AUD_PUBLIC.REG_SURVEY RS 
LEFT JOIN AUD_PUBLIC.REG_SURVEY_1 RS1 ON RS.ID = RS1.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_2_1 RS21 ON RS.ID = RS21.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_2_2 RS22 ON RS.ID = RS22.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_2_3 RS23 ON RS.ID = RS23.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_3 RS3 ON RS.ID = RS3.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_4 RS4 ON RS.ID = RS4.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_5 RS5 ON RS.ID = RS5.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_6 RS6 ON RS.ID = RS6.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_7 RS7 ON RS.ID = RS7.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_8 RS8 ON RS.ID = RS8.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_9 RS9 ON RS.ID = RS9.SURVEY_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY_10 RS10 ON RS.ID = RS10.SURVEY_ID
GROUP BY RS.SURVEY_AUDIT_ID) A ON FA.ID = A.SURVEY_AUDIT_ID
WHERE FA.IS_ACTIVE = 1
GROUP BY FA.CHECK_DEPARTMENT_ID, CD.DEPARTMENT_NAME
ORDER BY FA.CHECK_DEPARTMENT_ID`;

async function postGuitsetgel(context) {
  let query = baseQuery;

  const binds = {};

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.postGuitsetgel = postGuitsetgel;
