const oracledb = require("oracledb");
const database = require("../services/database.js");

const baseQuery = `SELECT FA.CHECK_DEPARTMENT_ID, CD.DEPARTMENT_NAME, COUNT(SE.ENT_ID) SEND,  COUNT(EE.ENT_ID) SENT,
SUM(A1.S1_SAVE) S1_SAVE, SUM(A1.S1_SENT) S1_SENT, SUM(A1.S1_HAM) S1_HAM,
SUM(A21.S1_SAVE) S21_SAVE, SUM(A21.S1_SENT) S21_SENT, SUM(A21.S1_HAM) S21_HAM,
SUM(A22.S1_SAVE) S22_SAVE, SUM(A22.S1_SENT) S22_SENT, SUM(A22.S1_HAM) S22_HAM,
SUM(A23.S1_SAVE) S23_SAVE, SUM(A23.S1_SENT) S23_SENT, SUM(A23.S1_HAM) S23_HAM,
SUM(A3.S1_SAVE) S3_SAVE, SUM(A3.S1_SENT) S3_SENT, SUM(A3.S1_HAM) S3_HAM,
SUM(A4.S1_SAVE) S4_SAVE, SUM(A4.S1_SENT) S4_SENT, SUM(A4.S1_HAM) S4_HAM,
SUM(A5.S1_SAVE) S5_SAVE, SUM(A5.S1_SENT) S5_SENT, SUM(A5.S1_HAM) S5_HAM,
SUM(A6.S1_SAVE) S6_SAVE, SUM(A6.S1_SENT) S6_SENT, SUM(A6.S1_HAM) S6_HAM,
SUM(A7.S1_SAVE) S7_SAVE, SUM(A7.S1_SENT) S7_SENT, SUM(A7.S1_HAM) S7_HAM,
SUM(A8.S1_SAVE) S8_SAVE, SUM(A8.S1_SENT) S8_SENT, SUM(A8.S1_HAM) S8_HAM,
SUM(A9.S1_SAVE) S9_SAVE, SUM(A9.S1_SENT) S9_SENT, SUM(A9.S1_HAM) S9_HAM,
SUM(A10.S1_SAVE) S10_SAVE, SUM(A10.S1_SENT) S10_SENT, SUM(A10.S1_HAM) S10_HAM
FROM FAS_ADMIN.FAS_AUDIT FA
INNER JOIN FAS_ADMIN.REF_CHECK_DEPARTMENT CD ON FA.CHECK_DEPARTMENT_ID = CD.ID
INNER JOIN AUD_PUBLIC.REF_SURVEY_ENTITY SE ON FA.ID = SE.SURVEY_AUDIT_ID
LEFT JOIN FAS_ADMIN.FAS_ENT_EMAIL EE ON FA.ID = EE.FAS_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_1 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A1 ON FA.ID = A1.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_2_1 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A21 ON FA.ID = A21.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_2_2 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A22 ON FA.ID = A22.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_2_3 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A23 ON FA.ID = A23.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_3 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A3 ON FA.ID = A3.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_4 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A4 ON FA.ID = A4.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_5 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A5 ON FA.ID = A5.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_6 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A6 ON FA.ID = A6.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_7 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A7 ON FA.ID = A7.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_8 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A8 ON FA.ID = A8.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_9 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A9 ON FA.ID = A9.SURVEY_AUDIT_ID
LEFT JOIN (SELECT 
R.SURVEY_AUDIT_ID,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT,
(CASE WHEN COUNT(RS1.ID) > 0 AND R.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM
FROM AUD_PUBLIC.REG_SURVEY R
INNER JOIN AUD_PUBLIC.REG_SURVEY_10 RS1 ON R.ID = RS1.SURVEY_ID
GROUP BY R.SURVEY_AUDIT_ID, R.SURVEY_STATUS_ID) A10 ON FA.ID = A10.SURVEY_AUDIT_ID
WHERE FA.IS_ACTIVE = 1
GROUP BY FA.CHECK_DEPARTMENT_ID, CD.DEPARTMENT_NAME
ORDER BY FA.CHECK_DEPARTMENT_ID`;

async function postGuitsetgel(context) {
  let query = baseQuery;

  const binds = {};

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.postGuitsetgel = postGuitsetgel;
