const oracledb = require("oracledb");
const database = require("../services/database.js");

const baseQuery = `SELECT 
CD.DEPARTMENT_NAME,
CASE WHEN RBT.BUDGET_TYPE_ID = 3 AND SE.BUDGET_TYPE_ID = 5 THEN 'Анхан шатны эмнэлэг' ELSE RBT.BUDGET_SHORT_NAME END BUDGET_NAME,
COUNT(SE.ENT_ID) SEND,
COUNT(EE.ENT_ID) SENT,
COUNT(SE.ENT_ID) - COUNT(EE.ENT_ID) ZURUU,
SUM(CASE WHEN A1.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S1_SAVE, SUM(CASE WHEN A1.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S1_SENT, SUM(CASE WHEN A1.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S1_HAM, SUM(CASE WHEN A1.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S1_NEW,
SUM(CASE WHEN A21.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S21_SAVE, SUM(CASE WHEN A21.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S21_SENT, SUM(CASE WHEN A21.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S21_HAM, SUM(CASE WHEN A21.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S21_NEW,
SUM(CASE WHEN A22.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S22_SAVE, SUM(CASE WHEN A22.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S22_SENT, SUM(CASE WHEN A22.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S22_HAM, SUM(CASE WHEN A22.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S22_NEW,
SUM(CASE WHEN A23.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S23_SAVE, SUM(CASE WHEN A23.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S23_SENT, SUM(CASE WHEN A23.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S23_HAM, SUM(CASE WHEN A23.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S23_NEW,
SUM(CASE WHEN A3.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S3_SAVE, SUM(CASE WHEN A3.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S3_SENT, SUM(CASE WHEN A3.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S3_HAM, SUM(CASE WHEN A3.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S3_NEW,
SUM(CASE WHEN A4.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S4_SAVE, SUM(CASE WHEN A4.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S4_SENT, SUM(CASE WHEN A4.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S4_HAM, SUM(CASE WHEN A4.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S4_NEW,
SUM(CASE WHEN A5.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S5_SAVE, SUM(CASE WHEN A5.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S5_SENT, SUM(CASE WHEN A5.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S5_HAM, SUM(CASE WHEN A5.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S5_NEW,
SUM(CASE WHEN A6.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S6_SAVE, SUM(CASE WHEN A6.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S6_SENT, SUM(CASE WHEN A6.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S6_HAM, SUM(CASE WHEN A6.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S6_NEW,
SUM(CASE WHEN A7.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S7_SAVE, SUM(CASE WHEN A7.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S7_SENT, SUM(CASE WHEN A7.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S7_HAM, SUM(CASE WHEN A7.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S7_NEW,
SUM(CASE WHEN A8.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S8_SAVE, SUM(CASE WHEN A8.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S8_SENT, SUM(CASE WHEN A8.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S8_HAM, SUM(CASE WHEN A8.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S8_NEW,
SUM(CASE WHEN A9.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S9_SAVE, SUM(CASE WHEN A9.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S9_SENT, SUM(CASE WHEN A9.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S9_HAM, SUM(CASE WHEN A9.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S9_NEW,
SUM(CASE WHEN A10.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) S10_SAVE, SUM(CASE WHEN A10.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) S10_SENT, SUM(CASE WHEN A10.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) S10_HAM, SUM(CASE WHEN A10.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) S10_NEW
FROM FAS_ADMIN.FAS_AUDIT FA 
INNER JOIN FAS_ADMIN.REF_CHECK_DEPARTMENT CD ON FA.CHECK_DEPARTMENT_ID = CD.ID
INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID 
INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
LEFT JOIN FAS_ADMIN.FAS_DOCUMENT_DATA FDD ON FA.ID = FDD.FAS_AUDIT_ID AND FDD.IS_ACTIVE = 1 AND FDD.IND_ID IN (287, 344)
INNER JOIN AUD_PUBLIC.REF_SURVEY_ENTITY SE ON FA.ID = SE.SURVEY_AUDIT_ID
INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
LEFT JOIN FAS_ADMIN.FAS_ENT_EMAIL EE ON FA.ID = EE.FAS_AUDIT_ID AND FA.ENT_ID = EE.ENT_ID
LEFT JOIN AUD_PUBLIC.REG_SURVEY A1 ON FA.ID = A1.SURVEY_AUDIT_ID AND A1.SURVEY_ID = 1
LEFT JOIN AUD_PUBLIC.REG_SURVEY A21 ON FA.ID = A21.SURVEY_AUDIT_ID AND A21.SURVEY_ID = 2
LEFT JOIN AUD_PUBLIC.REG_SURVEY A22 ON FA.ID = A22.SURVEY_AUDIT_ID AND A22.SURVEY_ID = 3
LEFT JOIN AUD_PUBLIC.REG_SURVEY A23 ON FA.ID = A23.SURVEY_AUDIT_ID AND A23.SURVEY_ID = 4
LEFT JOIN AUD_PUBLIC.REG_SURVEY A3 ON FA.ID = A3.SURVEY_AUDIT_ID AND A3.SURVEY_ID = 5
LEFT JOIN AUD_PUBLIC.REG_SURVEY A4 ON FA.ID = A4.SURVEY_AUDIT_ID AND A4.SURVEY_ID = 6
LEFT JOIN AUD_PUBLIC.REG_SURVEY A5 ON FA.ID = A5.SURVEY_AUDIT_ID AND A5.SURVEY_ID = 7
LEFT JOIN AUD_PUBLIC.REG_SURVEY A6 ON FA.ID = A6.SURVEY_AUDIT_ID AND A6.SURVEY_ID = 8
LEFT JOIN AUD_PUBLIC.REG_SURVEY A7 ON FA.ID = A7.SURVEY_AUDIT_ID AND A7.SURVEY_ID = 9
LEFT JOIN AUD_PUBLIC.REG_SURVEY A8 ON FA.ID = A8.SURVEY_AUDIT_ID AND A8.SURVEY_ID = 10
LEFT JOIN AUD_PUBLIC.REG_SURVEY A9 ON FA.ID = A9.SURVEY_AUDIT_ID AND A9.SURVEY_ID = 11
LEFT JOIN AUD_PUBLIC.REG_SURVEY A10 ON FA.ID = A10.SURVEY_AUDIT_ID AND A10.SURVEY_ID = 12
WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND FA.ID != 3322 --AND FA.CHECK_DEPARTMENT_ID = 17
GROUP BY CD.ID, CD.DEPARTMENT_NAME, RBT.BUDGET_TYPE_ID, SE.BUDGET_TYPE_ID, RBT.BUDGET_SHORT_NAME
ORDER BY CD.ID, RBT.BUDGET_TYPE_ID, SE.BUDGET_TYPE_ID,RBT.BUDGET_SHORT_NAME`;

async function postGuitsetgel(context) {
  let query = baseQuery;

  const binds = {};

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.postGuitsetgel = postGuitsetgel;

const baseUnsentQuery = `SELECT 
FA.ID,
CD.DEPARTMENT_NAME,
FA.AUDIT_CODE,
NVL(FDD.IND_VALUE,AE.ENT_NAME) ENT_NAME, 
CASE WHEN RBT.BUDGET_TYPE_ID = 3 AND SE.BUDGET_TYPE_ID = 5 THEN 'Анхан шатны эмнэлэг' ELSE RBT.BUDGET_SHORT_NAME END BUDGET_NAME,
AO.ORG_REGISTER_NO,
EE.EMAIL
FROM FAS_ADMIN.FAS_AUDIT FA 
INNER JOIN FAS_ADMIN.REF_CHECK_DEPARTMENT CD ON FA.CHECK_DEPARTMENT_ID = CD.ID
INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID 
INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
LEFT JOIN FAS_ADMIN.FAS_DOCUMENT_DATA FDD ON FA.ID = FDD.FAS_AUDIT_ID AND FDD.IS_ACTIVE = 1 AND FDD.IND_ID IN (287, 344)
INNER JOIN AUD_PUBLIC.REF_SURVEY_ENTITY SE ON FA.ID = SE.SURVEY_AUDIT_ID
INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
LEFT JOIN FAS_ADMIN.FAS_ENT_EMAIL EE ON FA.ID = EE.FAS_AUDIT_ID AND FA.ENT_ID = EE.ENT_ID
INNER JOIN AUD_PUBLIC.REF_SURVEY_CONFIG SC ON SE.BUDGET_TYPE_ID = SC.BUDGET_TYPE_ID 
LEFT JOIN AUD_PUBLIC.REG_SURVEY RS ON SC.SURVEY_ID = RS.SURVEY_ID AND FA.ID = RS.SURVEY_AUDIT_ID
WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND FA.ID != 3322 AND EE.EMAIL IS NOT NULL AND RS.SURVEY_STATUS_ID = 1`;

async function postUnsent(context) {
  let query = baseUnsentQuery;

  const binds = {};
  binds.SURVEY_ID = context.survey_id;
  query += `\nAND SC.SURVEY_ID = :SURVEY_ID`;

  if (context.dep_id != null) {
    binds.DEPARTMENT_ID = context.dep_id;
    query += `\nAND FA.CHECK_DEPARTMENT_ID = :DEPARTMENT_ID`;
  }
  query += `\nORDER BY CD.ID, RBT.BUDGET_TYPE_ID, SE.BUDGET_TYPE_ID, RBT.BUDGET_SHORT_NAME`;
  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.postUnsent = postUnsent;

const baseQueryaAuditor = `SELECT FA.ID, FA.ENT_ID, FA.AUDIT_CODE, NVL(FDD.IND_VALUE,AE.ENT_NAME) ENT_NAME, 
CASE WHEN RBT.BUDGET_TYPE_ID = 3 AND SE.BUDGET_TYPE_ID = 5 THEN 'Анхан шатны эмнэлэг' ELSE RBT.BUDGET_SHORT_NAME END BUDGET_NAME,
COUNT(SC.SURVEY_ID) CNT_TOTAL,
SUM(CASE WHEN RS.SURVEY_STATUS_ID = 1 THEN 1 ELSE 0 END) CNT_NEW, 
SUM(CASE WHEN RS.SURVEY_STATUS_ID = 2 THEN 1 ELSE 0 END) CNT_SAVE, 
SUM(CASE WHEN RS.SURVEY_STATUS_ID = 3 THEN 1 ELSE 0 END) CNT_SENT, 
SUM(CASE WHEN RS.SURVEY_STATUS_ID = 4 THEN 1 ELSE 0 END) CNT_HAM, 
SUM(CASE WHEN RS.SURVEY_STATUS_ID = 5 THEN 1 ELSE 0 END) CNT_CONFIRM, 
SUM(CASE WHEN RS.SURVEY_STATUS_ID = 6 THEN 1 ELSE 0 END) CNT_RETURN
FROM FAS_ADMIN.FAS_AUDIT FA
INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
INNER JOIN FAS_ADMIN.FAS_ENT_EMAIL EE ON FA.ENT_ID = EE.ENT_ID
LEFT JOIN AUD_REG.SYSTEM_USER SU ON EE.CREATED_BY = SU.USER_ID
LEFT JOIN FAS_ADMIN.FAS_DOCUMENT_DATA FDD ON FA.ID = FDD.FAS_AUDIT_ID AND FDD.IS_ACTIVE = 1 AND FDD.IND_ID IN (287, 344)
LEFT JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
LEFT JOIN AUD_PUBLIC.REF_SURVEY_ENTITY SE ON FA.ID = SE.SURVEY_AUDIT_ID
LEFT JOIN AUD_PUBLIC.REF_SURVEY_CONFIG SC ON SE.BUDGET_TYPE_ID = SC.BUDGET_TYPE_ID 
LEFT JOIN AUD_PUBLIC.REG_SURVEY RS ON SC.SURVEY_ID = RS.SURVEY_ID AND FA.ID = RS.SURVEY_AUDIT_ID
WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 `;

async function postAuditorZadargaa(context) {
  let query = baseQueryaAuditor;

  const binds = {};
  if (context.usertype === "ADMIN") {
    query += `\n AND 1 = 1 `;
  } else {
    binds.USER_ID = context.userid;
    query += `\n AND CASE WHEN EE.UPDATED_BY IS NULL THEN EE.CREATED_BY ELSE EE.UPDATED_BY END = :USER_ID`;
  }
  query += `\n GROUP BY FA.ID, FA.ENT_ID, FA.AUDIT_CODE, NVL(FDD.IND_VALUE,AE.ENT_NAME),
  CASE WHEN RBT.BUDGET_TYPE_ID = 3 AND SE.BUDGET_TYPE_ID = 5 THEN 'Анхан шатны эмнэлэг' ELSE RBT.BUDGET_SHORT_NAME END`;
  query += `\n ORDER BY NVL(FDD.IND_VALUE,AE.ENT_NAME)`;
  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.postAuditorZadargaa = postAuditorZadargaa;
